config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
	get 'home/index'


resources :treinos

 resources :medidas

match 'contact' => 'contact#new', :via => :get
match 'contact' => 'contact#create', :via => :post

 resources :home

 resources :perfil

 match 'painel/index'  => 'painel#index' , via: [:get], as: :painel

 devise_for :users,  :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",
 	registrations: 'registrations' },  :path_names => {:sign_in => 'login', :sign_out => 'logout',
 		:sign_up => 'signup'}

 		match "/users/sign_in", :to => redirect("/users/login"), via: [:get], :status => 301

 		match "/users/sign_out", :to => redirect("/users/logout"), via: [:get], :status => 301
 		match "/users/sign_up", :to => redirect("/users/signup"), via: [:get], :status => 301

 	root 'home#index'


 end

app/models/treino.rb
class Treino < ActiveRecord::Base

	
	belongs_to :user

	validates_presence_of  :grupo_muscular, :desc_exercicio, :carga, :serie, :repeticoes

	def self.personal

	query = "UPDATE treinos t, users u SET t.personal_id = u.personal_id WHERE t.user_id = u.id"
	
	results = ActiveRecord::Base.connection.execute(query)

	end
         

end

app/controllers/treinos_controller.rb
class TreinosController < ApplicationController

  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  before_filter :authenticate_user!
  respond_to :html, :xml, :json


  def index
    
    if current_user.role == 'personal'
    @treinos  = Treino.where(:personal_id=>current_user.id).order('user_id ASC')
    else
    @treinos  = Treino.where(:user_id=>current_user.id).order('grupo_muscular ASC')
    end

  end

  def show
    @treino = Treino.where(:user_id=>current_user.id).find(params[:id])

  end

  def new
    @treino = Treino.new

  end

  def edit
    @treino = current_user.treinos.find(params[:id])
  
  end

  def create
    @treino = Treino.new(treino_params)
    @treino.user_id = current_user.id

    if @treino.save
      redirect_to @treino, notice: 'Treino adicionado com sucesso.'
     #  Treino.personal
    else
      render action: "index"
    end
  end

  def update
    @treino = Treino.find(params[:id])

    if @treino.update(treino_params)
      redirect_to @treino, notice: 'Treino atualizado com sucesso.'
     # Treino.personal
    else
      render action: "edit"
    end
  end

  def destroy
    @treino = Treino.find(params[:id])
    @treino.destroy
    redirect_to treinos_url
  end

  private
  def set_treino
    @treino = Treino.find(params[:id])
  end

  def treino_params
    params.require(:treino).permit(:grupo_muscular, :desc_exercicio, :carga, :serie, :repeticoes)
  end
end

app/views/treinos/_form.html.erb
	<%= bootstrap_form_for(@treino, inline_errors: true) do |f| %>
	
	<%= f.alert_message "Por favor, preencha corretamente os campos marcados.", error_summary: true %>

	<%= f.select :grupo_muscular, [[nil],["Peitoral"], ["Costas"], ["Braços"], ["Ombros"], ["Abdómen"], ["Pernas"]],
	label: 'Grupo muscular' %>

	<%= f.text_field :desc_exercicio, label: 'Exercício' %>

	<%= f.select :carga, [[nil],["Muito leve"], ["Leve"], ["Moderado"], ["Pesado"], ["Muito pesado"]],label:
	'Carga' %>

	<%= f.number_field :serie, label: "Séries"%>

	<%= f.number_field :repeticoes, label: "Repetições"%>

	<%= f.submit "Salvar",  class: "btn btn-success btn-lg pull-right " %>
	
	<% end %>

app/views/treinos/edit.html.erb
 <div class="col-md-6 col-md-offset-3 text-left">
	<div class="text-center">
<h1>Editar treino</h1>
</div>

<%= render 'form' %>
<br><br><br>

<%= link_to 'Mostrar', @treino %> |
<%= link_to 'Voltar', treinos_path %>
<br><br><br>

</div>

app/views/treinos/index.html.erb
<% breadcrumb :treinos, @treinos %>

<h1><%= title 'Meu Treino' %></h1>

<div class="table-responsive ">
  <table class="table">

    <th class='info'>Grupo muscular</th>
    <th class='info'>Exercício </th>
    <th class='info'>Carga</th>
    <th class='info'>Séries </th>
    <th class='info'>Repetições</th>
    <th class='info'></th>
    <tbody>
      <% @treinos.each do |treino| %>
      <tr>

        <td><%= treino.grupo_muscular %></td>
        <td><%= treino.desc_exercicio %></td>
        <td><%= treino.carga %></td>
        <td><%= treino.serie %></td>
        <td><%= treino.repeticoes %></td>
        <td><%= link_to 'Editar', edit_treino_path(treino) %></td>
        <%end%>
      </tr>
    </tbody>
    
  </table>
</div>

<%= link_to 'Novo Treino', new_treino_path %>

app/views/treinos/new.html.erb
 <div class="col-md-6 col-md-offset-3 text-left">
	<div class="text-center">
<h1>Novo treino</h1>
</div>

<%= render 'form' %>
<br><br><br>

<%= link_to 'Voltar', treinos_path %>
<br><br><br>

</div>

app/views/treinos/show.html.erb
<h1>Treino</h1>
<div class="table-responsive ">
	<table class="table">
		
		<th class='info'> Grupo muscular</th>
		<th class='info'>Exercício </th>
		<th class='info'>Carga</th>
		<th class='info'>Séries </th>
		<th class='info'>Repetições</th>
		<th class='info'></th>
		<tbody>
			<tr>
				<td><%= @treino.grupo_muscular %></td>
				<td><%= @treino.desc_exercicio %></td>
				<td><%= @treino.carga %></td>
				<td><%= @treino.serie %></td>
				<td><%= @treino.repeticoes %></td>
				<td><%= link_to 'Editar', edit_treino_path(@treino) %></td>

			</tr>
		</tbody>
		
	</table>
</div>

<%= link_to 'Voltar', treinos_path %>