config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
	get 'home/index'


resources :treinos

 resources :medidas

match 'contact' => 'contact#new', :via => :get
match 'contact' => 'contact#create', :via => :post

 resources :home

 resources :perfil

 match 'painel/index'  => 'painel#index' , via: [:get], as: :painel

 devise_for :users,  :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",
 	registrations: 'registrations' },  :path_names => {:sign_in => 'login', :sign_out => 'logout',
 		:sign_up => 'signup'}

 		match "/users/sign_in", :to => redirect("/users/login"), via: [:get], :status => 301

 		match "/users/sign_out", :to => redirect("/users/logout"), via: [:get], :status => 301
 		match "/users/sign_up", :to => redirect("/users/signup"), via: [:get], :status => 301

 	root 'home#index'


 end

app/models/medida.rb
class Medida < ActiveRecord::Base
	
	belongs_to :user

	def self.personal

		@medida = Medida.all

		if not @medida.blank?

			query = "UPDATE medidas m, users u SET m.personal_id = u.personal_id WHERE m.user_id = u.id"
			
			results = ActiveRecord::Base.connection.execute(query)
		end
	end

end

app/controllers/medidas_controller.rb
class MedidasController < ApplicationController

  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  before_filter :authenticate_user!
  respond_to :html, :xml, :json

  def index
    @medidas  = Medida.where(:user_id=>current_user.id).order('created_at DESC')
   # Medida.personal
    
  end


 def show
  
  @medida = Medida.where(:user_id=>current_user.id).find(params[:id])
end

def new
  @medida = Medida.new

end

def edit

 @medida = current_user.medidas.find(params[:id])

end

def create

  @medida = Medida.new(medida_params)
  @medida.user_id = current_user.id


  if @medida.save
    redirect_to @medida, notice: 'Medida registrada com sucesso.'
   # Medida.personal
  else
    render action: "index"
  end

end

def update

 @medida = Medida.find(params[:id])

 if @medida.update(medida_params)
  redirect_to @medida, notice: 'Medida atualizada com sucesso.'
  # Medida.personal
else
  render action: "edit"
end
end

def destroy
  @medida = Medida.find(params[:id])
  @medida.destroy
  redirect_to medidas_url
end


private
def set_medida

  @medida = Medida.find(params[:id])

end

def medida_params
  params.require(:medida).permit(:data_medida, :peso, :torax, :ombro, :braco_d, :braco_e,
    :ante_braco_d, :ante_braco_e, :cintura, :quadril, :coxa_d, :coxa_e, :perna_d, :perna_e, :obs)
end
end

app/views/medidas/_form.html.erb
	
	<%= bootstrap_form_for(@medida, inline_errors: true) do |f| %>


	<%= f.date_select :data_medida, label: "Data" %>

	<%= f.number_field :peso, label: "Peso", append: "Kg", step: 0.1 %>

	<%= f.number_field :torax, label: "Tórax", append: "cm", step: 0.1%>

	<%= f.number_field :ombro, label: "Ombros", append: "cm", step: 0.1 %>

	<%= f.number_field :braco_d, label: "Braço direito", append: "cm", step: 0.1 %>

	<%= f.number_field :braco_e, label: "Braço esquerdo", append: "cm", step: 0.1 %>

	<%= f.number_field :ante_braco_d, label: "Antebraço direito", append: "cm", step: 0.1%>

	<%= f.number_field :ante_braco_e, label: "Antebraço esquerdo", append: "cm", step: 0.1%>

	<%= f.number_field :cintura, label: "Cintura", append: "cm", step: 0.1%>

	<%= f.number_field :quadril, label: "Quadril", append: "cm", step: 0.1 %>

	<%= f.number_field :coxa_d, label: "Coxa direita", append: "cm", step: 0.1 %>

	<%= f.number_field :coxa_e, label: "Coxa esquerda", append: "cm", step: 0.1%>

	<%= f.number_field :perna_d, label: "Panturrilha direita", append: "cm", step: 0.1 %>

	<%= f.number_field :perna_e, label: "Panturrilha esquerda", append: "cm", step: 0.1 %>

	<%= f.text_area :obs, label: "Observações"%>
		
	<%= f.submit "Salvar",  class: "btn btn-success btn-lg pull-right" %>
	
	<% end %>

app/views/medidas/edit.html.erb
<div class="col-md-6 col-md-offset-3 text-left">
	<div class="text-center">
<h1>Editar medida</h1>
</div>

<%= render 'form' %>
<br><br><br>

<%= link_to 'Apagar', @medida, method: :delete, data: { confirm: 'Você tem certeza?' } %> |

<%= link_to 'Mostrar', @medida %> |
<%= link_to 'Voltar', medidas_path %>

<br><br><br>

</div>

app/views/medidas/index.html.erb
<% breadcrumb :medidas, @medidas %>

<h1><%= title 'Minhas Medidas' %></h1>
 <% meta description: 'Visualizar avaliação biométrica corporal' %>
<div class="table-responsive" id="medidas">

  <table class="table">
    <th class="info">Data</th>
    <th class="info">Peso</th>
    <th class="info">Tórax</th>
    <th class="info">Ombro</th>
    <th class="info">Braço direito</th>
    <th class="info">Braço esquerdo</th>
    <th class="info">Antebraço direito</th>
    <th class="info">Antebraço esquerdo</th>
    <th class="info">Cintura</th>
    <th class="info">Quadril</th>
    <th class="info">Coxa direita</th>
    <th class="info">Coxa esquerda</th>
    <th class="info">Perna direta</th>
    <th class="info">Perna esquerda</th>
    <th class="info">Observação</th>
    <th class="info">    </th>


    <tbody>
      <% @medidas.each do |medida| %>
      <tr>
        <td><%= medida.data_medida.strftime("%d/%m/%Y") %></td>
        <td><%= medida.peso %></td>
        <td><%= medida.torax %></td>
        <td><%= medida.ombro %></td>
        <td><%= medida.braco_d %></td>
        <td><%= medida.braco_e %></td>
        <td><%= medida.ante_braco_d %></td>
        <td><%= medida.ante_braco_e %></td>
        <td><%= medida.cintura %></td>
        <td><%= medida.quadril %></td>
        <td><%= medida.coxa_d %></td>
        <td><%= medida.coxa_e %></td>
        <td><%= medida.perna_d %></td>
        <td><%= medida.perna_e %></td>
        <td><%= medida.obs %></td>
        <td><%= link_to 'Editar', edit_medida_path(medida) %></td>

    </tr>
    <% end %>
</tbody>
</table>

</div>
<%= link_to 'Nova Medida', new_medida_path %>

app/views/medidas/new.html.erb
<div class="col-md-6 col-md-offset-3 text-left">
	<div class="text-center">
<h1>Novas medidas</h1>
</div>

<%= render 'form' %>
<br><br><br>

<%= link_to 'Voltar', medidas_path %>
<br><br><br>
</div>

app/views/medidas/show.html.erb
<h1>Medidas</h1>
<p>
  <strong>Data medida:</strong>
  <%= @medida.data_medida.strftime("%d/%m/%Y") %>
</p>

<p>
  <strong>Peso:</strong>
  <%= @medida.peso.to_s+" Kg"%>
</p>

<p>
  <strong>Torax:</strong>
  <%= @medida.torax %>
</p>

<p>
  <strong>Ombro:</strong>
  <%= @medida.ombro %>
</p>

<p>
  <strong>Braco d:</strong>
  <%= @medida.braco_d %>
</p>

<p>
  <strong>Braco e:</strong>
  <%= @medida.braco_e %>
</p>

<p>
  <strong>Ante braco d:</strong>
  <%= @medida.ante_braco_d %>
</p>

<p>
  <strong>Ante braco e:</strong>
  <%= @medida.ante_braco_e %>
</p>

<p>
  <strong>Cintura:</strong>
  <%= @medida.cintura %>
</p>

<p>
  <strong>Quadril:</strong>
  <%= @medida.quadril %>
</p>

<p>
  <strong>Coxa d:</strong>
  <%= @medida.coxa_d %>
</p>

<p>
  <strong>Coxa e:</strong>
  <%= @medida.coxa_e %>
</p>

<p>
  <strong>Perna d:</strong>
  <%= @medida.perna_d %>
</p>

<p>
  <strong>Perna e:</strong>
  <%= @medida.perna_e %>
</p>

<p>
  <strong>Obs:</strong>
  <%= @medida.obs %>
</p>

<%= link_to 'Editar', edit_medida_path(@medida) %> |
<%= link_to 'Voltar', medidas_path %>