config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
	get 'home/index'


resources :treinos

 resources :medidas

match 'contact' => 'contact#new', :via => :get
match 'contact' => 'contact#create', :via => :post

 resources :home

 resources :perfil

 match 'painel/index'  => 'painel#index' , via: [:get], as: :painel

 devise_for :users,  :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",
 	registrations: 'registrations' },  :path_names => {:sign_in => 'login', :sign_out => 'logout',
 		:sign_up => 'signup'}

 		match "/users/sign_in", :to => redirect("/users/login"), via: [:get], :status => 301

 		match "/users/sign_out", :to => redirect("/users/logout"), via: [:get], :status => 301
 		match "/users/sign_up", :to => redirect("/users/signup"), via: [:get], :status => 301

 	root 'home#index'


 end

app/views/layouts/_footer.html.erb
<div id="footer">
	<div class="conteiner">
		<div class="row">

			<div class="col-md-4">

			</div>

			<div class="col-md-4" id="p2"> 

				<br>

				<%= link_to (image_tag "google-256.png",class: "social-icon" ), 'https://plus.google.com/114926340790891601148', rel: 'publisher',  :target => "_blank"%> 
				<%= link_to (image_tag "facebook-256.png",class: "social-icon"), 'https://www.facebook.com/pages/MuscleSys/1019521451407294',  :target => "_blank" %> 
				<%= link_to (image_tag "twitter-256.png",class: "social-icon" ), 'https://twitter.com/Muscle_Sys',  :target => "_blank" %> 

				<%= link_to (image_tag "email-256.png",class: "social-icon" ), '#contato',:data => { :toggle =>"modal" } %>

				<h4>© 2014 MuscleSys. Todos os direitos reservados. <br> Desenvolvido por  <%= link_to('Aristeu Roriz Neto', 'http://aristeuroriz.github.io', :target => '_blank', class: "arneti"  )%> </h4>

				<h4>Brasil / Goiás</h4>
				<%=image_tag "brasil_goias.jpg", class: "band" %>


			</div>

			<div class="col-md-4">



			</div>
		</div>

		<div id="contato" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="contatoLabel" aria-hidden="true">
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
						<h3 id="contatoLabel">Gostaríamos muito de ouvir de você</h3>
					</div>
					<div class="modal-body">
						
						<%= render template: "contact/new"%>

					</div>
					<div class="modal-footer">
						<button class="btn" data-dismiss="modal" aria-hidden="true">Fechar</button>
					</div>
				</div>
			</div>
		</div>


		<!-- Modal de seleção de aluno -->

		<% if user_signed_in? %>

		<div class="modal fade" id="aluno" tabindex="-1" role="dialog" aria-labelledby="Aluno" >
			<div class="modal-dialog">
				<div class="modal-content">

					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span >&times;</span></button>
						<h4 class="modal-title" id="myModalLabel">Escolher o aluno para visualizar o perfil</h4>
					</div>

					<div class="modal-body">


						<!-- Início do select box do usuário -->
						<% if current_user.role == "personal" or current_user.admin == true %>

						<% @users = User.where(:personal_id => current_user.id).order(:first_name) %>
						<%  @users.each do |user| %>

						<%= link_to (user.first_name+" "+user.last_name),"/admin", :class=> '' %><br/>

						

						<% end %>
						<% end %>
						<!-- Fim do select box do usuário -->
						

					</div>

					<div class="modal-footer">
						<button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
					</div>
				</div>
			</div>
		</div>

		<% end %>

		<!-- Fim ||| Modal de seleção de aluno -->

		

	</div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar-default navbar-fixed-top" role="navigation" id="menu">

				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bar" style="margin-top: 4%;">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<%= link_to((image_tag "logo_400x91.png", class: "logo col-lg-12", title: "Home"), root_path) %>
				</div>

				<div class="collapse navbar-collapse" id="bar">

					<div class="container">
						<%= render "layouts/navigation" %>
					</div>

				</div><!-- /.navbar-collapse -->
			</nav>

app/views/layouts/_messages.html.erb
<% unless flash.blank? %>
<% flash.each do |type, message| %>

<div class="alert" id="alert">
	<button class="close" data-dismiss="alert" >×</button>
	<%= message %>
</div>
  <%= javascript_include_tag "alert.js" %>
<% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<script type="text/javascript">
    $(document).on("ready page:change", function() {
        $('.tag-tooltip').tooltip();
    });
</script>

<% if user_signed_in? %>
<div class="left-menu">
    <ul class="nav navbar-nav">
        <li><%= link_to('Dashboard', painel_path, :method=> 'get', :class=> 'fonte-menu')%></li>
        <li><%= link_to('Treino', treinos_path , :class=> 'fonte-menu')%></li> 
        <li><%= link_to('Medidas', medidas_path, :class=> 'fonte-menu' )%></li>  
    </ul>
</div>
<div class="user-menu">
    <div class="dropdown pull-right">

        <% if current_user.image_url? %>

        <%= content_tag(:button, class: "profile-menu dropdown-toggle fonte-menu", id: "dropdownMenu1", :data => { :toggle =>"dropdown" }) do %>

        <%= (image_tag current_user.image_url, :style => "width:40px;height:40px;vertical-align:middle; border:5pxsolid;border-radius:50px;") +'<span>'.html_safe+" "+current_user.first_name+" "+current_user.last_name+" "+'</span><b class="caret"></b>'.html_safe do %>

        <% end %>
        <% end %>

        <% else %>

        <%= content_tag(:button, class: "profile-menu dropdown-toggle fonte-menu", id: "dropdownMenu1", :data => { :toggle =>"dropdown" }) do %>

        <%= (image_tag current_user.avatar.url, :style => "width:40px;height:40px;vertical-align:middle; border:5pxsolid;border-radius:50px;") +'<span>'.html_safe+" "+current_user.first_name+" "+current_user.last_name+" "+'</span><b class="caret"></b>'.html_safe do %>

        <% end %>
        <% end %>



        <% end %>

        <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
            <li><%=link_to "Ver perfil", '/perfil', class: 'fonte-menu',
                :method=> 'get'%></li>

                <% if current_user.role == "admin" and current_user.admin == true %>

                <li><%= link_to 'Administrar', '/admin' , :class=> 'fonte-menu'%></li>
                <% end %>

                <% if current_user.role == "personal" or current_user.role == "admin"%>

                <li><%= link_to 'Meus alunos', '#aluno',:data => { :toggle =>"modal" }, :class=> 'fonte-menu'%></li>

                <% end %>


                <li><%= link_to 'Sair', destroy_user_session_path, :method=>'delete', :class=> "fonte-menu" %></li>
            </ul>
        </div>
    </div>



    <% else %>

    <div class="out-left-menu">
        <ul class="nav navbar-nav">
            <li><%= link_to('Home', root_path , :class=> 'fonte-menu')%> </li>
            <li><%= link_to('Blog', root_path , :class=> 'fonte-menu')%></li> 
        </ul>
    </div>
    <div class="out-right-menu">
        <ul class="nav navbar-nav pull-right">

            <li><%= link_to('Criar conta grátis', new_user_registration_path, :method=> 'get' , :class=> 'fonte-menu')%></li>

            <li><%= link_to 'Entrar', new_user_session_path,:data => { :toggle =>"login" }, :class=> 'fonte-menu'%></li>

        </ul>
    </div>

    <% end %>

app/views/layouts/_termos.html.erb
TERMOS DE USO DO APLICATIVO MUSCLESYS VIA WEB

O site musclsys.com.br de um aplicativo web voltado para ativadades esportivas.
Ao utilizar qualquer material deste site, você está concordando com os Termos de Uso deste Serviço
abaixo descritos. Se não concorda com eles, não use o site nem qualquer material nele contido.

FASES DE TESTES ALFA E BETA

Durante as fases iniciais do aplicativo musclesys, onde serão testadas todas as funcionalidades implementadas,
bem como serão inseridas outras funcionalidades específicas, o musclesys.com.br não garante a permanência dos
dados do usuário que forem cadastradas neste período.

A saber, atualmente o musclesys.com.br encontra-se em fase de testes "Alfa" e neste período, devido aos
ajustes a serem feitos, os dados dos usuários podem não permanecer na base de dados.

TERMOS DE USO

O acesso ao site musclsys.com.br é gratuito temporariamente. O musclsys.com.br poderá criar áreas de acesso
exclusivo aos seus clientes ou para terceiros especialmente autorizados. O visitante poderá usar o site
musclsys.com.br apenas para fins legais.

O visitante não poderá usar o site musclsys.com.br ou seus serviços para publicar, enviar, distribuir ou
divulgar nenhum material ou informação de caráter difamatório, obsceno ou ilícito, inclusive informações de
propriedade exclusiva pertencentes a outras pessoas ou empresas, bem como marcas registradas ou informações
protegidas por direitos autorais, sem a expressa autorização do detentor desses direitos. Ainda, o visitante
não poderá usar o site musclsys.com.br para obter ou divulgar informações pessoais, inclusive endereços na
Internet, sobre os usuários do site.

O musclsys.com.br empenha-se em manter a qualidade, atualidade e autenticidade das informações do site. Entretanto,
não é responsável pelas conseqüências de quaisquer falhas que possam eventualmente existir no site, ou por possíveis
lucros cessantes ou danos decorrentes dessas falhas. O visitante não deve ter como pressuposto que o site ou seu
conteúdo sejam isentos de erros, ou que serão adequados ao objetivo particular que o visitante tem
em mente ao usá-lo.

O musclsys.com.br poderá, a seu exclusivo critério e em qualquer tempo, modificar ou desativar o site, bem como
limitar, cancelar ou suspender seu uso ou o acesso ao site e/ou fazer modificações nestes Termos de Uso.

DIREITOS AUTORAIS E MARCAS

Os documentos e informações contidos no musclsys.com.br constituem materiais protegidos por direitos autorais,
pertencentes ao musclsys.com.br e seus respectivos fornecedores de informações. A reprodução ou armazenamento de
materiais recuperados a partir deste serviço sujeitará os infratores às penas das leis aplicáveis em matéria de
direito autoral. As imagens contidas neste website são aqui incorporadas apenas para fins de visualização, e,
salvo autorização expressa por escrito, não podem ser gravadas ou baixadas via download.

O termo musclsys.com.br , seu logotipo, bem como todos os elementos característicos da tecnologia desenvolvida e
aqui apresentada, sob a forma da articulação de bases de dados, constituem marcas registradas e propriedades
intelectuais privadas e todos os direitos decorrentes de seu registro são assegurados por lei.

PROPRIEDADE DOS MATERIAIS

Os materiais são protegidos por copyright nacionais e por leis internacionais de copyright. Não podem ser
copiados, reproduzidos, modificados, publicados, atualizados, postados, transmitidos ou distribuídos de
qualquer maneira sem autorização prévia e por escrito do musclsys.com.br que não cede nenhum direito
implícito ou explícito sob nenhuma patente, copyright, marca registrada ou informações de segredo comercial.

Outros direitos podem ser cedidos pelo musclsys.com.br por escrito ou quando explicitado em alguma licença
especial ou contrato.O musclsys.com.br pode cancelar esta licença a qualquer momento se não cumprido os
termos desta licença.

EXCLUSÃO

Os materiais são fornecidos "como estão" sem nenhuma garantia explícita ou implícita, inclusive garantias
de comerciabilidade, não-infração de propriedade intelectual, ou de adequação a qualquer objetivo específico.
Em nenhum caso o musclsys.com.br ou os seus fornecedores serão responsabilizados por quaisquer danos incluindo
(sem limitação), lucros cessantes, interrupção de negócio, ou perda de informação que resultem do uso ou da
incapacidade de usar os materiais, mesmo que o musclsys.com.br tenha sido avisada da possibilidade de tais danos.
Como algumas jurisdições proíbem a exclusão ou limitação da responsabilidade por danos, conseqüências ou
incidentais, as limitações acima podem não ser aplicadas a você. O musclsys.com.br não garante a precisão ou
integridade das informações, textos, gráficos, links e outros itens dos materiais. O musclsys.com.br pode
alterar os materiais ou produtos, objetos desta licença a qualquer tempo e sem aviso prévio. O musclsys.com.br
não se compromete a atualizar os materiais.

AVISO ESPECÍFICO PARA OS DOCUMENTOS DISPONÍVEIS

Os documentos e gráficos correlatos publicados neste site podem conter imprecisões técnicas ou erros
tipográficos. Alterações serão incluídas periodicamente nas informações aqui contidas. O musclsys.com.br
e/ou seus respectivos fornecedores poderão efetuar aperfeiçoamentos e/ou alterações no(s) produto(s)
aqui descrito(s) a qualquer tempo.

Em nenhuma hipótese, o musclsys.com.br e/ou seus respectivos fornecedores serão responsáveis por qualquer dano
especial, conseqüencial ou qualquer outro dano direto ou indireto decorrente da impossibilidade de uso, perda de
dados ou lucros, seja em razão de contrato, culpa ou dolo, resultante ou relativo ao uso ou desempenho do software,
dos documentos, do fornecimento ou falha no fornecimento de serviços, ou de informações disponíveis neste site.
Ademais, o musclsys.com.br tem como objetivo somente propiciar aos usuários rapidez e facilidade a serviços e
informações on-line, sem que isto seja uma certificação dos mesmos. Sobre o conteúdo de artigos, o musclsys.com.br
não se responsabiliza pelos mesmos, vez que tais textos não são de sua autoria, bem como não traduzem, necessariamente,
a opinião do site, pois este instrumento tem o atributo único de reunir as diversas opiniões acerca dos diversos
temas na rede mundial de computadores.

SUBMISSÃO DO USUÁRIO E COLABORADOR

Qualquer material, informação, artigos ou outras comunicações que forem transmitidas ou colocadas neste site
serão considerados informação não confidencial. O musclsys.com.br não terá obrigação alguma com respeito à essas
informações de terceiros. É terminantemente proibido colocar ou transmitir para ou deste site, qualquer material
ilegal, ameaçador, difamador, obsceno, pornográfico ou outro que possa violar qualquer lei. O musclsys.com.br
reserva-se o direito de restringir o acesso às informações cedidas por terceiros aos seus assinantes e colaboradores.

SALAS DE CHAT

O musclsys.com.br poderá, mas não é obrigado, a monitorar ou revistar qualquer área no site onde usuários transmitem
ou colocam informações ou se comunicam somente entre si, incluindo, mas não limitado a salas de chat, centro de
mensagens ou outros foros de usuários, e o conteúdo de quaisquer dessas comunicações. Porém, o musclsys.com.br não
será responsável legalmente pelo conteúdo de qualquer uma dessas comunicações, sejam elas afetadas ou não pelas
leis de copyright, calúnia, privacidade, obscenidade ou outros.

LINKS PARA OUTROS MATERIAIS

Os sites apontados não estão sob o controle do musclsys.com.br que não é responsável pelo conteúdo de qualquer
site apontado ou qualquer link contido num site apontado. O musclsys.com.br reserva o direito de eliminar qualquer
link ou programa de ligação a qualquer momento. O musclsys.com.br não endossa firmas ou produtos para quem aponta
links e reserva o direito de anotar este fato nas suas páginas na web.

LEIS APLICÁVEIS

Este site é controlado e operado pelo musclsys.com.br a partir de seu escritório na cidade de Luziânia
estado de Goiás e não garante que os materiais do site sejam adequados ou estejam disponíveis para uso
em outras localidades. Seu acesso é proibido em territórios onde o conteúdo dos materiais seja considerado
ilegal. Aqueles que optarem por acessar este site a partir de outras localidades o farão por iniciativa
própria e serão responsáveis pelo cumprimento das leis locais aplicáveis.
Os materiais não deverão ser usados ou exportados em descumprimento das leis brasileiras sobre exportação.
Qualquer pendência com relação aos materiais será dirimida pelas leis brasileiras.

INFORMAÇÕES SOBRE MARCAS REGISTRADAS

As marcas registradas do musclsys.com.br só podem ser usadas publicamente com autorização expressa.
O uso destas marcas registradas em publicidade e promoção de produtos deve ser adequadamente informado.

RECLAMAÇÕES SOBRE VIOLAÇÃO DE DIREITOS AUTORAIS

O musclsys.com.br respeita a propriedade intelectual de outras pessoas ou empresas e solicitamos aos nossos membros
que façam o mesmo. Caso seu trabalho tenha sido copiado e esteja acessível no serviço do musclsys.com.br de maneira
que constitua uma violação de direito autoral, você poderá notificar o musclsys.com.br , fornecendo ao responsável
por direitos autorais do musclsys.com.br as seguintes informações:

a)identificação do URL ou outro local específico no site onde o material em relação ao qual se reclama a existência de violação pode ser localizado;

b)uma descrição dos trabalhos protegidos por direitos autorais em relação aos quais se reclama a existência de
violação, inclusive o URL (ou seja, o endereço da pagina na web) do local onde o trabalho protegido por direito
autoral pode ser encontrado, ou uma cópia do trabalho protegido por direito autoral;

c) o endereço, número de telefone e endereço de e-mail do autor;

d) uma declaração feita pelo autor, sob pena de perjúrio, de que as informações acima, contidas em sua Notificação,
são corretas e que se trata de detentor do direito autoral ou a pessoa autorizada a atuar em nome do detentor do
direito autoral.

O responsável pelo musclsys.com.br para notificação de quaisquer reclamações de violação de direitos autorais
pode ser contatado pelo formulário fale conosco do site ou via postal: Av. Alfredo Nasser, Qd. 10, Res. Águas
Claras, Apto 701-B

© Copyright 2015 MuscleSys - By Arneti Tecnologia.
Proibida sua reprodução total ou parcial.

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-br">
<head>
	<meta charset="utf-8">
	<%= viewport_meta_tag(:maximum_scale => "1.0") %>

	<%= metamagic site: "MuscleSys", title: [:site, :title, ], separator: " — ",
	description: "App web fitness para acompanhamento nos treinos diários. Musculação, condicionamento e emagrecimento com estatísticas de qualquer lugar em qualquer hora",
	author: "https://www.linkedin.com/in/aristeuroriz",
	canonical:  "http://musclesys.com.br/", 
	twitter: {card: "summary", site: "@Muscle_Sys"}
	%>

	<meta name="google-site-verification" content="uI_7in9sLC6XQhr2XppMvD-uXRpeRSkZ4f-GhvMqRmA" />

	<meta name="msvalidate.01" content="F453CB8C9A435F59E3DFFF805C9B7F74" />

	<script src='https://www.google.com/recaptcha/api.js?hl=pt-BR'></script>

	<%= favicon_link_tag 'favicon.ico' %>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= include_gon %>
	<%= csrf_meta_tags %>
</head>
<body>

	<div id="wrap">
		<header>	
			
			<%= render 'layouts/header' %>
			
		</header>

		<div id="main" role="main">

			<div class="container">
				<div class="content">
					<div class="row-fluid">

						<div class="text-center">
							
							<%= bootstrap_flash %> 
							
						</div>

						<%= yield %>

					</div>

					<br><br>

					<div class="col-md-4 col-md-offset-8 text-center">

						<%= breadcrumbs pretext: "Você está aqui: ", display_single_fragment: false, style: :bootstrap, separator: "" %>
					</div>

				</div>
			</div>

		</div>
	</div>
	
	<%= render 'layouts/footer' %>


	<script type="text/javascript">
		(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
			(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
			m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

		ga('create', 'UA-57355885-1', 'auto');
		ga('send', 'pageview');
	</script>

</body>
</html>